### ISSUE TITLE
Error: not in scope: 'e' in http put method

### ISSUE THREAD

**Issue by abrim** [tlaitinen/yesod-dsl#33]
Not sure if I'm doing something wrong, the following route results in a compile error

route /location/#LocationId {
  put {
    update Location identified by $1 with {
      name = $request.name,
      parent = $request.parent
    };
  }
}

the relevant part of the putLocationLocationIdR function is:

    runDB_result <- do
        e2 <- do
    
            return $ e {
                            locationParent = attr_parent
                    ,
                            locationName = attr_name
    
                }

but 'e' is never defined prior.

Similarly changing the put to 'update Location identified by $1;' results in attr_parent & attr_name not being defined.

**Comment by tlaitinen** [comment]
Thanks for reporting this. I added  https://github.com/tlaitinen/yesod-dsl/blob/master/tests/tests.ydsl to keep track of possible regressions.
