### ISSUE TITLE
Duplicate Instance Declarations

### ISSUE THREAD

**Issue by jjmias** [tlaitinen/yesod-dsl#36]
Hello,

We are getting the following error when building.

```
Handler/Api/Internal.hs:200:10:
        Duplicate instance declarations:
          instance FromJSON Day -- Defined at Handler/Api/Internal.hs:200:10
          instance FromJSON Day
            -- Defined in ‘aeson-extra-0.2.2.0:Data.Aeson.Compat’
```

This is related to https://github.com/yesodweb/persistent/issues/180.

A little about our setup is that we use stack and are building to the lts-3.14 snapshot.  We would go down a couple snapshots, but we require one of the later snapshots because we also use keter.  We haven't yet figured out what the oldest snapshot we could use would be to get all of our functionality to work.

We really appreciate this library!

Update - This has to do with the 0.2.2.0 version of aeson-extra.  Building to snapshot lts-3.13 worked and that had aeson-extra-0.2.1.0.  

With that being said I would like to turn this into an enhancement request that we support stack and put this into a snapshot.

**Comment by tlaitinen** [comment]
Thanks for reporting this. I'll fix it on Monday. Have a nice weekend!

**Comment by tlaitinen** [comment]
The commit https://github.com/tlaitinen/yesod-dsl/commit/1371daf58f0d081ab01f205230159710942c8a69 should make it possible to compile it with aeson-extra-0.2.2.0 . FromJSON Day is not compiled by default but can be enabled with a preprocessor flag in cpp-options: -DFromJSON_Day .
