### ISSUE TITLE
Alter Database Column Name

### ISSUE THREAD

**Issue by jjmias** [tlaitinen/yesod-dsl#40]
When changing the field name of an Entity's object, the database is not changed leaving mismatched column names and field names.

I would prefer to not have to manually alter the column's name as the objects are handled by yesod-dsl.

**Comment by tlaitinen** [comment]
Migration is covered by Database.Persist . The default yesod scaffolding uses safe migration which refuses to drop columns not defined in the Persistent database definition. You can switch to unsafe migration but it increases the risk of accidentally losing some data.

**Comment by jjmias** [comment]
@tlaitinen Thank you for the information, that helped us fix the migration. A+
